### ISSUE TITLE
Excel Support is Broken

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-data-embed#52]
https://adobeioruntime.net/api/v1/web/helix/helix-services/data-embed@1.3.1/https://adobe.sharepoint.com/sites/TheBlog/_layouts/15/guestaccess.aspx?share=ESR1N29Z7HpCh1Zfs_0YS_gB4gVSuKyWRut-kNcHVSvkew&email=helix%40adobe.com&e=hx0OUl returns an error 500.

**Comment by trieloff** [comment]
```
acquire token with ROPC.
Error while refreshing access token Error: Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
    at Logger.createError (/code/helix-data-embed/node_modules/adal-node/lib/log.js:216:13)
    at WSTrustResponse.parse (/code/helix-data-embed/node_modules/adal-node/lib/wstrust-response.js:278:23)
    at WSTrustRequest._handleRSTR (/code/helix-data-embed/node_modules/adal-node/lib/wstrust-request.js:187:21)
    at /code/helix-data-embed/node_modules/adal-node/lib/wstrust-request.js:228:12
    at Request._callback (/code/helix-data-embed/node_modules/adal-node/lib/util.js:134:5)
```

**Comment by trieloff** [comment]
@tripodsan do you have an idea what could cause this? I think this is the blocker for #53

**Comment by tripodsan** [comment]
you probably use the wrong client_id.... I can take a look

**Comment by tripodsan** [comment]
@trieloff Fetching the workbook works for me... but then, the worksheet has no table.... I added some checks to the excel handler.
